sources:
  - type: maven
    path: pom.xml
    modules:
      - integration_tests
      - jar_artifact
linkReplacements:
build:
  runnerOs: ubuntu-24.04
  freeDiskSpace: false
  exasolDbVersions:
    - "2026.1.0"
    - "2025.1.10"
  workflows:
    - name: ci-build.yml
      stepCustomizations:
        - action: INSERT_AFTER
          job: matrix-build
          stepId: enable-testcontainer-reuse
          content:
            name: Fix "VM Crashed" error by allowing unprivileged user namespaces
            id: fix-vm-crashed
            run: sudo sysctl -w kernel.apparmor_restrict_unprivileged_userns=0
        - action: INSERT_AFTER
          job: matrix-build
          stepId: enable-testcontainer-reuse
          content:
            name: Create test.properties
            id: create-test-config
            run: |
              echo "${{ secrets.GCS_SERVICE_ACCOUNT_KEY_JSON_BASE64 }}" > google-service-account-key.base64
              cat google-service-account-key.base64 | base64 --decode > google-service-account-key.json
              echo "serviceAccountEmail = ${{ secrets.GCS_SERVICE_ACCOUNT_EMAIL }}" > test.properties
              echo "googleProjectId = ${{ secrets.GCS_PROJECT_ID }}" >> test.properties
              echo "privateKeyPath = google-service-account-key.json" >> test.properties
