sources:
  - type: maven
    path: pom.xml
    modules:
      - integration_tests
      - jar_artifact
linkReplacements:
build:
  # UDFs in Exasol 7.1 require Ubuntu 20.04
  runnerOs: ubuntu-20.04
  freeDiskSpace: false
  exasolDbVersions:
    - "8.32.0"
    - "7.1.30"
  workflows:
    - name: ci-build.yml
      stepCustomizations:
        - action: INSERT_AFTER
          job: matrix-build
          stepId: enable-testcontainer-reuse
          content:
            name: Create test.properties
            id: create-test-config
            run: |
              echo "${{ secrets.GCS_SERVICE_ACCOUNT_KEY_JSON }}" > google-service-account-key.json
              echo "serviceAccountEmail = ${{ secrets.GCS_SERVICE_ACCOUNT_EMAIL }}" > test.properties
              echo "googleProjectId = ${{ secrets.GCS_PROJECT_ID }}" >> test.properties
              echo "privateKeyPath = google-service-account-key.json" >> test.properties
