sources:
  - type: maven
    path: pom.xml
    modules:
      - integration_tests
      - jar_artifact
linkReplacements:
build:
  # UDFs in Exasol 7.1 require Ubuntu 20.04
  runnerOs: ubuntu-20.04
  freeDiskSpace: false
  exasolDbVersions:
    - "8.32.0"
    - "7.1.30"
