sources:
  - type: maven
    path: pom.xml
    modules:
      - integration_tests
      - jar_artifact
linkReplacements:
excludes:
build:
  runnerOs: ubuntu-20.04
  freeDiskSpace: false
  exasolDbVersions:
    - "7.1.25"
    - "8.24.0"